######################################################################
# Automatically generated by qmake (3.0) Wed Jan 7 17:17:56 2015
######################################################################

QT += testlib
TEMPLATE = app
TARGET = test
INCLUDEPATH += .

# Input
HEADERS += ../DES.h
SOURCES += testEncryption.cpp ../DES.cpp
